name: Build Docker Images for ARM and AMD

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-arm:
    name: Build ARM64 image
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        run: |
          docker build -t ghcr.io/nautilus-unipd/raspberry-setup:arm64 .
          docker push ghcr.io/nautilus-unipd/raspberry-setup:arm64

  build-amd:
    name: Build AMD64 image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AMD64 image
        run: |
          docker build -t ghcr.io/nautilus-unipd/raspberry-setup:amd64 .
          docker push ghcr.io/nautilus-unipd/raspberry-setup:amd64
