name: Build Docker Image

# Build every time this file or the docker file changes
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  # Build on a VM with the latest version of ubuntu
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/nautilus-unipd/raspberry-setup:latest
